---
-
  name: Create a data stotage directory
  file:
    state: directory
    path: "{{storage_dir_path}}/data"
    owner: "{{default_permission}}"
    group: "{{default_permission}}"
    mode: 0755
  become: yes
-
  name: "copy data content to storage"
  command: "cp -rf /azlamp/data/{{source_dns_name}} {{storage_dir_path}}/data"
  become: yes

-
  name: "rename data content folder name from source to target"
  command: "mv {{storage_dir_path}}/data/{{source_dns_name}} {{storage_dir_path}}/data/{{target_dns_name}}"
  become: yes

