- hosts: 127.0.0.1
  connection: local
  roles:
    - sshkeyconfig
    - copysitetostorage
    - copydatatostorage
    - databaseexport
    - updateconfig
    - createNcopystoragezip
    - copytoblobstorage

- hosts: webservers
  roles:
    - importFromStorage
    - unzipstorage
    - databaseimport
    - replication
