---
- name: Create a .tar.gz archive of storage
  archive:
    path: "{{storage_dir_path}}"
    format: tar.gz
    dest: /home/azureadmin/storage.tar.gz

-
  name: "copy storage.zip file to remote host"
  command: rsync -avz /home/{{user_name}}/storage.tar.gz {{user_name}}@{{vm_ip}}:/home/{{user_name}}
  #no_log: false
