---
- name: Create a .tar archive of storage
  archive:
    path: "{{storage_dir_path}}"
    format: {{file_format}}
    dest: /home/{{user_name}}/storage.tar

-
  name: "copy storage.tar file to remote host"
  command: scp /home/{{user_name}}/storage.tar {{user_name}}@{{vm_ip}}:/home/{{user_name}}
