--- 
- name: Extract storage.tar.gz
  unarchive:
    src: "/home/azureadmin/storage.tar"
    dest: /home/azureadmin/
    owner: "{{default_permission}}"
    group: "{{default_permission}}"
    copy: no
  become: yes

-
  name: "move site contents"
  command: "mv {{storage_dir_path}}/site/{{target_dns_name}} /azlamp/html/"
  become: yes

-
  name: "move data contents"
  command: "mv {{storage_dir_path}}/data/{{target_dns_name}} /azlamp/data/"
  become: yes
