--- 
-
  name: Create a main stotage directory
  file:
    state: directory
    path: "{{storage_dir_path}}"
    owner: "{{default_permission}}"
    group: "{{default_permission}}"
    mode: 0755
  become: yes
-
  name: Create a site stotage directory
  file:
    state: directory
    path: "{{storage_dir_path}}/site"
    owner: "{{default_permission}}"
    group: "{{default_permission}}"
    mode: 0755
  become: yes
-
  name: "copy site content to storage"
  command: "cp -rf /azlamp/html/{{source_dns_name}}/ {{storage_dir_path}}/site"
  become: yes

-
  name: "rename site content folder name from source to target"
  command: "mv {{storage_dir_path}}/site/{{source_dns_name}}/ {{storage_dir_path}}/site/{{target_dns_name}}"
  become: yes

