---
- name: Install MySQL 
  apt: 
    name: mysql-server
    state: latest
  become: yes

- name: export database
  shell: "mysqldump -h {{source_db_server_name}} -u {{source_db_login_name}} -p{{source_db_pass}} {{source_db_name}} > {{storage_dir_path}}/database.sql"
   become: yes
